Git interaction fails if project located at path with spaces
codecov/codecov-exe pull request #21
Opened 2017-07-29 22:12 UTC by justdmitry

If GIT repo is located at path with spaces (`D:\My Documents\My Repos\...`) then any call to `git` executable fails because `RepoRoot` is not recognized as single parameter.

Value should be quoted (on Windows, not sure about other platforms).

2017-07-29 22:17 UTC, larzw commented
Thanks for the PR! I'll take a look shortly and hopefully get a release out.

2017-07-30 00:37 UTC, larzw requested changes
This change requires the mocks to be updated correctly in `GitTests.cs`. For example, `terminal.Run("git", $"-C {Directory.GetCurrentDirectory()} rev-parse --abbrev-ref HEAD").Returns("develop");` Will need some quotes.

2017-07-30 00:39 UTC, larzw commented
What happens if the user supplies a quoted repoRoot from the command line? Will this quote it twice? git -C ""foo""? Would you be willing to add some unit tests? Thanks again for help out with this 😄

2017-08-03 17:46 UTC, justdmitry commented
Yep, that was bad idea to make PR at 2AM :(

> What happens if the user supplies a quoted repoRoot from the command line?

From nothing to crash (even without my changes):

With `--root "D:\My Documents\myrepo"` nothing changes - CommandLine.Parser eats quotes.

With `--root ""D:\My Documents\myrepo""` all breaks - CommandLine.Parser produce `D:\My` as value of `RepoRoot` and `VersionControlSystem.LoadSourceCode()` fails when enumerating unexisting folder.

With `--root "\"D:\My Documents\myrepo\""` all breaks again - CommandLine.Parser "understands" this escaped quotes and gives `"D:\My Documents\myrepo"` (with quotes) value to `RepoRoot`, and then `FileSystem.NormalizedPath` fails on `Path.GetFullPath` with "The given path's format is not supported."

So, currently user is not able to provide quoted repoRoot from command line.

---

I agree to revert changes to `Git.cs` and make changes to `FileSystem.cs` (check for spaces in `absolutePath` and append quotes around if found), but 17 of 150 existing tests becomes unstable - they depends on current project location. They use current directory, which (in new logic) should be quoted if contains spaces and should not otherwise.

One workaround is to duplicate all substitutes like:

    terminal.Run("git", $"-C {Directory.GetCurrentDirectory()} rev-parse HEAD").Returns("11");
    terminal.Run("git", $"-C \"{Directory.GetCurrentDirectory()}\" rev-parse HEAD").Returns("11");

But this not looks good. Any better ideas?

2017-08-03 19:57 UTC, larzw commented
Thanks for looking into all this!...I'll put some though into it this weekend and let you know if I have any ideas too. I'm completely open to all your ideas :).

2017-08-07 17:00 UTC, larzw commented
I've included your change in PR 24 and merged it into the main branch. I just updated the unit tests. I should get a release out in the next few day's. Thanks again for the help 😄 .

2017-08-07 17:00 UTC, closed without merging